# Generated by Django 4.0.4 on 2023-08-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_words', models.TextField(blank=True, null=True, verbose_name='Составные  слова')),
            ],
            options={
                'verbose_name': 'Список составных слов для 1-4 класса',
                'verbose_name_plural': 'Составные слова для 1-4 класса',
            },
        ),
    ]
