# Generated by Django 4.0.4 on 2023-08-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0002_compoundword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compoundword',
            options={'verbose_name': 'Кошмок сөздөр', 'verbose_name_plural': 'Кошмок сөздөр'},
        ),
    ]
