# Generated by Django 4.0.4 on 2023-08-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0003_alter_compoundword_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundword',
            name='compound_words',
            field=models.TextField(blank=True, null=True, verbose_name='Кошмок сөздөр'),
        ),
    ]
