# Generated by Django 4.2.4 on 2023-09-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0004_alter_compoundword_compound_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgtext',
            name='compound_words_p',
            field=models.FloatField(blank=True, null=True, verbose_name='Татаал сөздөрдүн % '),
        ),
        migrations.AlterField(
            model_name='kgtext',
            name='lcwords_p',
            field=models.FloatField(blank=True, null=True, verbose_name='% Многосложных  слов для 1-4 кл.'),
        ),
    ]
