# Generated by Django 4.2.4 on 2023-09-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0005_kgtext_compound_words_p_alter_kgtext_lcwords_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgtext',
            name='q_compound_words',
            field=models.FloatField(blank=True, null=True, verbose_name='Кошмок сөздөрдүн саны'),
        ),
    ]
