# Generated by Django 4.2.4 on 2023-09-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0006_kgtext_q_compound_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kgtext',
            old_name='longw_q',
            new_name='multisyllabic_wq',
        ),
        migrations.AlterField(
            model_name='kgtext',
            name='book_author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автору'),
        ),
        migrations.AlterField(
            model_name='kgtext',
            name='book_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Чыгарманын аты'),
        ),
        migrations.AlterField(
            model_name='kgtext',
            name='sentence_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='Сүйлөмдүрдүн орточо узундугу сөздөр менен'),
        ),
        migrations.AlterField(
            model_name='kgtext',
            name='sentence_q',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сүйлөмдөрдүн жалпы саны'),
        ),
        migrations.AlterField(
            model_name='kgtext',
            name='syllables_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='Сөздөрдүн орточо узундугу муундар менен'),
        ),
        migrations.AlterField(
            model_name='kgtext',
            name='words_q',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сөздөрдүн саны'),
        ),
    ]
