# Generated by Django 4.2.4 on 2023-09-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0007_rename_longw_q_kgtext_multisyllabic_wq_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kgtext',
            old_name='lcwords_q',
            new_name='compound_w_q',
        ),
    ]
