# Generated by Django 4.2.4 on 2023-09-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0008_rename_lcwords_q_kgtext_compound_w_q'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kgtext',
            name='lcwords_p',
        ),
        migrations.AlterField(
            model_name='kgtext',
            name='compound_w_q',
            field=models.FloatField(blank=True, null=True, verbose_name='Татаал жана кош сөздөрдүн саны'),
        ),
    ]
