# Generated by Django 4.2.4 on 2023-09-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0009_remove_kgtext_lcwords_p_alter_kgtext_compound_w_q'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kgtext',
            old_name='compound_words_p',
            new_name='all_compound_words_p',
        ),
    ]
