# Generated by Django 4.2.4 on 2023-09-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0010_rename_compound_words_p_kgtext_all_compound_words_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kgtext',
            old_name='q_compound_words',
            new_name='complex_w_q',
        ),
    ]
