# Generated by Django 4.2.4 on 2023-09-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0011_rename_q_compound_words_kgtext_complex_w_q'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freqword',
            options={'verbose_name': 'Көп колдонулган сөздөр', 'verbose_name_plural': 'Көп колдонулган сөздөр'},
        ),
        migrations.AlterModelOptions(
            name='lcword',
            options={'verbose_name': 'Татаал сөздөр', 'verbose_name_plural': 'Татаал сөздөр'},
        ),
        migrations.AlterModelOptions(
            name='rareword',
            options={'verbose_name': 'Сейрек сөздөр', 'verbose_name_plural': 'Сейрек сөздөр'},
        ),
        migrations.RenameField(
            model_name='g1level',
            old_name='g1_longw_q_l1',
            new_name='g1_multisyllabic_wq_l1',
        ),
        migrations.AlterField(
            model_name='freqword',
            name='freq_words',
            field=models.TextField(blank=True, null=True, verbose_name='Көп колдонулган сөздөр'),
        ),
        migrations.AlterField(
            model_name='kgtext',
            name='fw_p',
            field=models.FloatField(blank=True, null=True, verbose_name='Көп колдонулган сөздөрдүн %'),
        ),
        migrations.AlterField(
            model_name='kgtext',
            name='fw_q',
            field=models.FloatField(blank=True, null=True, verbose_name='Көп колдонулган сөздөр'),
        ),
        migrations.AlterField(
            model_name='kgtext',
            name='level_result',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сунушталган класс'),
        ),
        migrations.AlterField(
            model_name='kgtext',
            name='multisyllabic_wq',
            field=models.FloatField(blank=True, null=True, verbose_name='Көп муунду сөздөрдүн саны'),
        ),
        migrations.AlterField(
            model_name='kgtext',
            name='rareword_p',
            field=models.FloatField(blank=True, null=True, verbose_name='Сейрек сөздөрдүн %'),
        ),
        migrations.AlterField(
            model_name='kgtext',
            name='rareword_q',
            field=models.FloatField(blank=True, null=True, verbose_name='Сейрек сөздөрдүн саны'),
        ),
        migrations.AlterField(
            model_name='kgtext',
            name='uniq_w',
            field=models.IntegerField(blank=True, null=True, verbose_name='Уникалдуу сөздөрдүн саны'),
        ),
        migrations.AlterField(
            model_name='lcword',
            name='lc_words',
            field=models.TextField(blank=True, null=True, verbose_name='Татаал сөздөр'),
        ),
        migrations.AlterField(
            model_name='rareword',
            name='rare_words',
            field=models.TextField(blank=True, null=True, verbose_name='Сейрек сөздөр'),
        ),
    ]
