# Generated by Django 4.2.4 on 2023-09-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0012_alter_freqword_options_alter_lcword_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='g1level',
            old_name='g1_longw_q_l3',
            new_name='g1_multisyllabic_wq_l2',
        ),
        migrations.RemoveField(
            model_name='g1level',
            name='g1_longw_q_l2',
        ),
    ]
