# Generated by Django 4.2.4 on 2023-09-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0014_g1level_g1_multisyllabic_wq_l3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='g1level',
            name='g1_complexw_q_l1',
            field=models.FloatField(blank=True, null=True, verbose_name='Кошмок сөздөрдүн саны 1.1'),
        ),
        migrations.AddField(
            model_name='g1level',
            name='g1_complexw_q_l2',
            field=models.FloatField(blank=True, null=True, verbose_name='Кошмок сөздөрдүн саны 1.2'),
        ),
        migrations.AddField(
            model_name='g1level',
            name='g1_complexw_q_l3',
            field=models.FloatField(blank=True, null=True, verbose_name='Кошмок сөздөрдүн саны 1.3'),
        ),
    ]
