# Generated by Django 4.2.4 on 2023-09-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0015_g1level_g1_complexw_q_l1_g1level_g1_complexw_q_l2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='g2level',
            old_name='g2_longw_q_l1',
            new_name='g2_multisyllabic_wq_l1',
        ),
        migrations.RenameField(
            model_name='g2level',
            old_name='g2_longw_q_l2',
            new_name='g2_multisyllabic_wq_l2',
        ),
    ]
