# Generated by Django 4.2.4 on 2023-09-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0016_rename_g2_longw_q_l1_g2level_g2_multisyllabic_wq_l1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='g2level',
            name='g2_complexw_q_l1',
            field=models.FloatField(blank=True, null=True, verbose_name='Кошмок сөздөрдүн саны 2.1'),
        ),
        migrations.AddField(
            model_name='g2level',
            name='g2_complexw_q_l2',
            field=models.FloatField(blank=True, null=True, verbose_name='Кошмок сөздөрдүн саны 2.2'),
        ),
    ]
