# Generated by Django 4.2.4 on 2023-09-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0017_g2level_g2_complexw_q_l1_g2level_g2_complexw_q_l2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='g3level',
            old_name='g3_longw_q_l1',
            new_name='g3_multisyllabic_wq_l1',
        ),
        migrations.RenameField(
            model_name='g3level',
            old_name='g3_longw_q_l2',
            new_name='g3_multisyllabic_wq_l2',
        ),
    ]
