# Generated by Django 4.2.4 on 2023-09-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0018_rename_g3_longw_q_l1_g3level_g3_multisyllabic_wq_l1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='g3level',
            name='g3_complexw_q_l1',
            field=models.FloatField(blank=True, null=True, verbose_name='Кошмок сөздөрдүн саны 3.1'),
        ),
        migrations.AddField(
            model_name='g3level',
            name='g3_complexw_q_l2',
            field=models.FloatField(blank=True, null=True, verbose_name='Кошмок сөздөрдүн саны 3.2'),
        ),
    ]
