# Generated by Django 4.2.4 on 2023-09-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0019_g3level_g3_complexw_q_l1_g3level_g3_complexw_q_l2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='g4level',
            old_name='g4_longw_q_l1',
            new_name='g4_multisyllabic_wq_l1',
        ),
        migrations.RenameField(
            model_name='g4level',
            old_name='g4_longw_q_l2',
            new_name='g4_multisyllabic_wq_l2',
        ),
    ]
