# Generated by Django 4.2.4 on 2023-09-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uz', '0002_compoundword_kgtext_delete_uztext_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kgText',
            new_name='uzText',
        ),
    ]
