# Generated by Django 4.2.4 on 2023-10-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uz', '0005_alter_uztext_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compoundword',
            options={'verbose_name': 'Кўшма сўзлар', 'verbose_name_plural': 'Кўшма сўзлар'},
        ),
        migrations.AlterModelOptions(
            name='freqword',
            options={'verbose_name': 'Кўп ишлатиладиган сўзларин', 'verbose_name_plural': 'Кўп ишлатиладиган сўзларин'},
        ),
        migrations.AlterModelOptions(
            name='lcword',
            options={'verbose_name': 'Қийин сўзлар', 'verbose_name_plural': 'Қийин сўзлар'},
        ),
        migrations.AlterModelOptions(
            name='rareword',
            options={'verbose_name': 'Ноёб сўзлар', 'verbose_name_plural': 'Ноёб сўзлар'},
        ),
        migrations.AlterField(
            model_name='compoundword',
            name='compound_words',
            field=models.TextField(blank=True, null=True, verbose_name='Кўшма сўзлар'),
        ),
        migrations.AlterField(
            model_name='freqword',
            name='freq_words',
            field=models.TextField(blank=True, null=True, verbose_name='Кўп ишлатиладиган сўзларин'),
        ),
        migrations.AlterField(
            model_name='lcword',
            name='lc_words',
            field=models.TextField(blank=True, null=True, verbose_name='Қийин сўзлар'),
        ),
        migrations.AlterField(
            model_name='rareword',
            name='rare_words',
            field=models.TextField(blank=True, null=True, verbose_name='Ноёб сўзлар'),
        ),
        migrations.AlterField(
            model_name='uztext',
            name='syllables_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='Средняя длина слов в слога'),
        ),
    ]
