# Generated by Django 4.2.4 on 2023-10-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uz', '0006_alter_compoundword_options_alter_freqword_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='g1level',
            options={'verbose_name': '1-синф учун даража', 'verbose_name_plural': '1-синф учун даража'},
        ),
        migrations.AlterModelOptions(
            name='g2level',
            options={'verbose_name': '2-синф учун даража', 'verbose_name_plural': '2-синф учун даража'},
        ),
        migrations.AlterModelOptions(
            name='g3level',
            options={'verbose_name': '3-синф учун даража', 'verbose_name_plural': '3-синф учун даража'},
        ),
        migrations.AlterModelOptions(
            name='g4level',
            options={'verbose_name': '4-синф учун даража', 'verbose_name_plural': '4-синф учун даража'},
        ),
    ]
