# Generated by Django 4.2.4 on 2023-10-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uz', '0008_alter_uztext_fw_p'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uztext',
            options={'verbose_name': 'Ўзбек тилидаги матнлар', 'verbose_name_plural': 'Ўзбек тилидаги матнлар'},
        ),
    ]
