# Generated by Django 4.2.4 on 2023-09-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rutext',
            old_name='longw_q',
            new_name='multisyllabic_wq',
        ),
    ]
