# Generated by Django 4.2.4 on 2023-09-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0002_rename_longw_q_rutext_multisyllabic_wq'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_words', models.TextField(blank=True, null=True, verbose_name='Кошмок сөздөр')),
            ],
            options={
                'verbose_name': 'Составные слова',
                'verbose_name_plural': 'Составные слова',
            },
        ),
    ]
