# Generated by Django 4.2.4 on 2023-09-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0003_compoundword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutext',
            name='grade',
        ),
    ]
